#Arreglos y Clases
##Matrices
Una matriz es un elemento de m por n elementos.
Sea la matriz \( A \) de tamaño \( m \times n \):

A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}


In [1]:
A=[[1,2,3],[4,5,6],[7,8,9]]
print (A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [3]:
B= [[21,34,40],[71,17,77],[78,81,28]]
print (B)

[[21, 34, 40], [71, 17, 77], [78, 81, 28]]


In [4]:
A+B

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [78, 81, 28]]

In [5]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
A[0][0]
[1,2,3]

[1, 2, 3]

##Vectores y Listas
L=A[0]

In [7]:
L=A[0]
M=B[0]

In [8]:
a=L[0]
b=M[0]
a+b

22

In [9]:
a==1

True

###Suma de "Vectores"

In [10]:
len(L)==len(M)

True

In [13]:
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
suma

[22, 36, 43]

In [14]:
suma=[L[i]+M[i] for i in range(3)]
suma

[22, 36, 43]

##Creación de funciones globales

La función para crear funcines es "def¨ que se cierra con un debug (print or return)

In [15]:
def Hola():
  print("Hola,me llamo Rodrigo")

In [16]:
Hola

<function __main__.Hola()>

In [24]:
def Saludar(s,n):
  print(f"Hola,me llamo {s} y tengo {n} años")

In [25]:
Saludar("Rodrigo",18)

Hola,me llamo Rodrigo y tengo 18 años


In [38]:
I = [ i for i in range{10}]

def par():
  for x in range(I):
    if x%2==0:
      print(f"{x} es par ")
    else:
      print(f"{x} es impar")

SyntaxError: invalid syntax (<ipython-input-38-a82953946f96>, line 1)

In [32]:
par(20)

0 es par 
1 es impar
2 es par 
3 es impar
4 es par 
5 es impar
6 es par 
7 es impar
8 es par 
9 es impar


In [44]:
def suma_vectorial(L,M):
  x = [L[i]+M[i] for i in range(len(L))]
  return x

In [45]:
L = [1,2,3]
M=[21,34,40]

suma_vectorial(L,M)

[22, 36, 43]

##Módulos o librerías


In [47]:
import math
from math import sqrt, pi

In [48]:
sqrt(68)

8.246211251235321

In [49]:
pi

3.141592653589793

#El Modulo Numpy
La función array


In [56]:
import numpy as np

L_vector = np.array(L)
M_vector = np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [60]:
C=[9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [61]:
A_matriz @ A_matriz

array([[66, 26, 11],
       [12, 37,  7],
       [25, 49, 34]])

In [62]:
A_matriz @ C_matriz

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])